version: "2.3"
services:
  app:
    build:
      dockerfile: Dockerfile.app
      context: ./app
    volumes:
      - ./app:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment: 
      - TZ=Asia/Seoul
    ports:
      - "8001:8001"
    networks:
    - backend
networks: 
  backend:
    driver: bridge